esercizio3: main.o manipola_date.o
	g++ main.o manipola_date.o -o esercizio3 -Wall -Wextra -Wpedantic

main.o: main.cpp
	g++ main.cpp -c -o main.o -Wall -Wextra -Wpedantic

manipola_date.o: manipola_date.cpp
	g++ manipola_date.cpp -c -o manipola_date.o -Wall -Wextra -Wpedantic

clean:
	rm main.o manipola_date.o esercizio3